apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nodejs-express
spec:
  selector:
    matchLabels:
      app: k8s-nodejs-express
  replicas: 4
  template:
    metadata:
      labels:
        app: k8s-nodejs-express
    spec:
      containers:
        - name: k8s-nodejs-express
          image: ahmedmahmoudo/nodejs-express-hello-world:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
